### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by H00dlum** [TheOnlyWayUp/Twitch-Chat-Joiner#1]
when launching the app

python3.8 async_twitch.py
Traceback (most recent call last):
  File "async_twitch.py", line 24, in <module>
    config = json.load(handler)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 18 (char 217)

I suspect the issue with my channels list.   It looks like this

"channels": [tfue,shroud],

if that isn't the problem, any idea what could be?

**Comment by TheOnlyWayUp** [comment]
Hi! Sorry for the late response (lmao). You're right about the channels list, setting it to:
```json
"channels": ["tfue", "shroud"],
```
would fix the issue!

Curious though, were you able to get it working?
